id: P7512BD2B
initial_creation_type: input
source_metadata:
  title: Khenmo Rigdzin Chödrön Series
  language: en
  description: 'Texts by Khenmo Rigdzin Chödrön (mkhan mo rig ''dzin chos sgron) of
    Larung Gar:'
  volume:
    f2178ed709164cca97ef9dadaf712dbb:
      title: An Exhortation to Tibetans
      parent: Advice
created_at: '2022-03-01T00:23:39.356994'
last_modified_at: '2022-03-01T00:23:39.357000'
